secret:
  confirm-url: https://api.tosspayments.com/v1/payments/confirm
  toss-url: https://api.tosspayments.com/v1/payments/
  payment-api-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

aes:
  secret-key: Rhcekfflsrkaskan5Rhcekfflsrkask1

password:
  encode:
    algorithm: PBKDF2WithHmacSHA1
    iterations: 8524
    keyLength: 128
    saltAlgorithm: SHA-256

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.145.75.81:3306/molly?serverTimezone=Asia/Seoul
    username: molly
    password: 5Molly!@#3
  server:
    timezone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB

jjwt:
  secret-key: YghJQDCgYOLtTKHH8TLtLdT9GaWQxE40ITOsGjGnc0Y=
  expiration-time: 3600000

file:
  storage: http://172.16.24.53:8081/image